@host = http://localhost:8080/orion/api/v1

# Rest Client for Visual Studio Code Extension

{{host}}/public/hello

###

{{host}}/protected/products
Authorization: Basic joao 123

### 

{{host}}/admin/products/-1
Authorization: Basic joao 123

###

{{host}}/admin/products/pageable?page=2&sort=name,desc&sort=id,asc
Authorization: Basic maria 123

###

{{host}}/admin/products
Authorization: Basic maria 123
Content-Type: application/json

{
    "id": 0,
    "name": "PRODUCT 251"
}