@host = http://localhost:8080/orion/api/v1

{{host}}
###

# Rest Client for Visual Studio Code Extension

{{host}}/public/hello

###

{{host}}/protected/products
Authorization: Basic maria 123

### 

{{host}}/admin/products/1
Authorization: Basic maria 123

### 

DELETE {{host}}/admin/products/2
Authorization: Basic maria 123

###

{{host}}/protected/products/pageable?size=3&sort=name,asc&sort=id,asc
Authorization: Basic maria 123

###

POST {{host}}/admin/products
Authorization: Basic maria 123
Content-Type: application/json

{
    "id": 0,
    "name": "251"
}

###

POST {{host}}/admin/products
Authorization: Basic maria 123
Content-Type: application/json

{
    "id": 0,
    "name": "PRODUCT 251"
}

###

POST {{host}}/admin/products
Authorization: Basic maria 123
Content-Type: application/json

{
    "id": 0,
    "name": "pp"
}