server:
  servlet:
    context-path: /orion/api

spring:
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    show-sql: true
    open-in-view: true
  datasource:
    url: jdbc:h2:mem:testDB;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 20
        one-indexed-parameters: true